name: Miworkflow

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar codigo
        run: |
          wget https://github.com/ulopeznovoa/AS-CI-CD-ej1.git
          unzip AS-CI-CD-ej1-main.zip

      - name: instalar pytest
        run: pip install pytest

      - name: usar pytest
        run: pytest test.py
