name: Miworkflow

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar codigo
        uses: git clone https://github.com/ulopeznovoa/AS-CI-CD-ej1.git

      - name: instalar pytest
        run: pip install pytest

      - name: usar pytest
        run: python3 test.py
